### PR TITLE
Add a `-p` option to support delta patches.

### PR DESCRIPTION
**Pull request by mrhappyasthma**
When specifying `-p` or `--previous`, only files that are newer
than the specified previous version will be downloaded.

### CODE REVIEW

**Comment by mrhappyasthma** [comment]
Fixes https://github.com/silentbugs/hon-client-scraper/issues/7

**Comment by silentbugs** [comment]
Nicely done. Python's `packaging` seems to be working with 3 digit versions, and doesn't specify what happens with 4-digit ones. Have you tested it with 4-digit versions (e.g. `3.3.6.1`)?

**Comment by mrhappyasthma** [comment]
Yeah, it works great. I've been using it for some time.
works

**Comment by silentbugs** [comment]
I was a bit quick to merge this, `packaging` version 3.0.7 doesn't seem to be available on pypi. I tried it with the latest available version `21.3` and it seems to work fine. Could you confirm this is the one you intended to use?

https://pypi.org/project/packaging/#history

**Comment by mrhappyasthma** [comment]
I'm not exactly sure what happened there. Perhaps a copy/paste error by me?

Yes, it should be `21.3`. That's what I currently have installed. Sorry about that!

**Comment by silentbugs** [comment]
No worries, test and pushed the fix!

**Pull request merged**
