### PR TITLE
Use python request.Session for file downloads

### PR DESCRIPTION
**Pull request by mrhappyasthma**
This should help with speeds (slightly) and decrease any risk of throttling.

### CODE REVIEW

**Review by silentbugs — COMMENTED** [review]
Maybe the same should be done for `get_manifest()` and the `patcher()`?

**Comment by mrhappyasthma** [comment]
That's probably a good idea. you know this code better than I do, too.

This was just the spot that I had the most issues, since it spends most of the time downloading files.

**Comment by mrhappyasthma** [comment]
I can try to update this PR when I get some downtime.

Splitting my time between backing up the downloads and working on the masterserver emulator project.

**Comment by silentbugs** [comment]
Merged the PR and changed the rest of the requests to use the same session

**Pull request merged**
